image:
  file: Dockerfile
#tasks:
#  - command: >
#       sbt
#      echo ROCKET_ADDRESS=$ROCKET_ADDRESS >> .env &&
#      echo ROCKET_PORT=$ROCKET_PORT >> .env &&
#      pg_start.sh &&
#      diesel setup &&
#      cargo build &&
#      cargo run
#ports:
# - port: 8000